#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	
	if [ "systemd" == "$INITSYS" ]; then
		ln -s /usr/lib/sodesk/sodesk /usr/bin/sodesk

		if [ -e /etc/systemd/system/sodesk.service ]; then
			rm /etc/systemd/system/sodesk.service /usr/lib/systemd/system/sodesk.service /usr/lib/systemd/user/sodesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/sodesk/files/systemd/sodesk.service /usr/lib/systemd/system/sodesk.service
		systemctl daemon-reload
		systemctl enable sodesk
		systemctl start sodesk
	fi
fi
